export const PUBLIC_KEY_GO = `
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDKclYFWaEPLnhBPUCpwWOn9Xet
fS9mRoK2Z9haKvY6PNXD2YECIUZO6YxHZDua9yOO5h/NK9u1rcJsST9ZFEm/ddGM
SUtcLd6Hl0bgNLJ2Ew9vK6TQ+1Ah0/2lcyMcp6Lsb5wOX7wADU/QymDP9bsSnaLy
2VhOjGudWc6EzHNE+QIDAQAB
-----END PUBLIC KEY-----
`
